import mongoose from 'mongoose';
import dotenv from 'dotenv';
dotenv.config();

const MONGO_URI = process.env.MONGO_URI || 'mongodb://localhost:27017/tourist-safety';

const placeSchema = new mongoose.Schema({}, { strict: false });
const hotelSchema = new mongoose.Schema({}, { strict: false });
const Place = mongoose.model('Place', placeSchema);
const Hotel = mongoose.model('Hotel', hotelSchema);

const places = [
    {
        name: 'Taj Mahal',
        location: 'Agra, Uttar Pradesh', city: 'Agra', state: 'Uttar Pradesh',
        address: 'Dharmapuri, Forest Colony, Tajganj, Agra, UP 282001',
        rating: 4.9,
        image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=800&q=80',
        history: 'The Taj Mahal is an ivory-white marble mausoleum commissioned in 1631 by Mughal emperor Shah Jahan to house the tomb of his beloved wife Mumtaz Mahal. Built over 22 years by 20,000 artisans, it is considered the finest example of Mughal architecture—a blend of Persian, Islamic, and Indian styles. It was designated a UNESCO World Heritage Site in 1983.',
        builtYear: '1631–1653', builtBy: 'Emperor Shah Jahan',
        timings: 'Sunrise to Sunset (Closed Fridays)', entryFee: '₹200 (Indian) / ₹1,100 (Foreign)',
        distanceFromDelhi: '233 km', routeFromDelhi: 'Take Yamuna Expressway (NH19) from Delhi — about 3 hrs by car. Gatimaan Express train from Hazrat Nizamuddin (90 min) or Shatabdi from New Delhi Station.',
        coordinates: { lat: 27.1751, lng: 78.0421 }, category: 'heritage', isVerified: true,
        verifiedBy: 'Ministry of Tourism, India', tags: ['UNESCO', 'Mughal', 'World Heritage', 'Marble'],
    },
    {
        name: 'Hawa Mahal',
        location: 'Jaipur, Rajasthan', city: 'Jaipur', state: 'Rajasthan',
        address: 'Hawa Mahal Rd, Badi Choupad, Pink City, Jaipur 302002',
        rating: 4.7,
        image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80',
        history: 'Hawa Mahal (Palace of Winds) was built in 1799 by Maharaja Sawai Pratap Singh. Its five-storey honeycomb facade has 953 small windows called "jharokhas" decorated with intricate latticework, allowing royal ladies to observe street festivals while remaining unseen. Designed to resemble the crown of Krishna, it is built from red and pink sandstone.',
        builtYear: '1799', builtBy: 'Maharaja Sawai Pratap Singh',
        timings: '9:00 AM – 5:00 PM', entryFee: '₹50 (Indian) / ₹200 (Foreign)',
        distanceFromDelhi: '282 km', routeFromDelhi: 'Take NH48 from Delhi towards Jaipur — about 4.5 hrs by car. Pink City Express or Shatabdi train from New Delhi Station to Jaipur Junction (4.5 hrs).',
        coordinates: { lat: 26.9239, lng: 75.8267 }, category: 'palace', isVerified: true,
        verifiedBy: 'Ministry of Tourism, India', tags: ['Rajasthan', 'Pink City', 'Royal', 'Architecture'],
    },
    {
        name: 'India Gate',
        location: 'New Delhi', city: 'New Delhi', state: 'Delhi',
        address: 'Kartavya Path, Rajpath, India Gate, New Delhi 110001',
        rating: 4.8,
        image: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=800&q=80',
        history: 'India Gate is a 42-metre-tall war memorial built in 1931, designed by Sir Edwin Lutyens. It commemorates the 70,000 soldiers of the British Indian Army who died during World War I. The Amar Jawan Jyoti (eternal flame) at its base honors soldiers of the 1971 Indo-Pakistani War. The memorial stands on the ceremonial Kartavya Path boulevard.',
        builtYear: '1921–1931', builtBy: 'Sir Edwin Lutyens',
        timings: 'Open 24 hours', entryFee: 'Free',
        distanceFromDelhi: '0 km (Heart of Delhi)', routeFromDelhi: 'Located in central New Delhi. Take Metro Blue Line to Central Secretariat — 10 min walk. Easily accessible via Kartavya Path.',
        coordinates: { lat: 28.6129, lng: 77.2295 }, category: 'monument', isVerified: true,
        verifiedBy: 'Ministry of Tourism, India', tags: ['War Memorial', 'National Monument', 'Delhi', 'Free Entry'],
    },
    {
        name: 'Qutb Minar',
        location: 'Mehrauli, New Delhi', city: 'New Delhi', state: 'Delhi',
        address: 'Mehrauli, New Delhi 110030',
        rating: 4.6,
        image: 'https://images.unsplash.com/photo-1515091943-9d5c0ad475af?auto=format&fit=crop&w=800&q=80',
        history: 'Qutb Minar is a 72.5-metre minaret and UNESCO World Heritage Site built in 1193 by Qutb-ud-Din Aibak after the defeat of Delhi\'s last Hindu kingdom. The five-storey tower of red sandstone and marble is the tallest brick minaret in the world. The complex includes the famous Iron Pillar of Delhi, which has not rusted in 1,600 years.',
        builtYear: '1193–1220', builtBy: 'Qutb-ud-Din Aibak',
        timings: 'Sunrise to Sunset', entryFee: '₹40 (Indian) / ₹600 (Foreign)',
        distanceFromDelhi: '15 km from Connaught Place', routeFromDelhi: 'Take Yellow Line Metro to Qutab Minar Station — 10 min walk. By road via NH48 through Mehrauli.',
        coordinates: { lat: 28.5245, lng: 77.1855 }, category: 'heritage', isVerified: true,
        verifiedBy: 'Ministry of Tourism, India', tags: ['UNESCO', 'Islamic Architecture', 'Medieval', 'Iron Pillar'],
    },
    {
        name: 'Amber Fort',
        location: 'Amer, Jaipur, Rajasthan', city: 'Jaipur', state: 'Rajasthan',
        address: 'Devisinghpura, Amer, Jaipur, Rajasthan 302001',
        rating: 4.8,
        image: 'https://images.unsplash.com/photo-1477587458883-47145ed31fd4?auto=format&fit=crop&w=800&q=80',
        history: 'Amber Fort (Amer Fort) is a UNESCO World Heritage Site and majestic hilltop fortress built in 1592 by Raja Man Singh I. Constructed from red sandstone and white marble, it overlooks Maota Lake and blends Hindu and Rajput architectural styles. The Sheesh Mahal (Hall of Mirrors) inside is considered one of the finest examples of mirror-work craftsmanship in the world.',
        builtYear: '1592', builtBy: 'Raja Man Singh I',
        timings: '8:00 AM – 5:30 PM', entryFee: '₹100 (Indian) / ₹500 (Foreign)',
        distanceFromDelhi: '290 km', routeFromDelhi: 'Take NH48 to Jaipur (4.5 hrs), then 11 km to Amer. Alternatively, take Shatabdi Express train to Jaipur Junction, then cab to fort.',
        coordinates: { lat: 26.9855, lng: 75.8513 }, category: 'heritage', isVerified: true,
        verifiedBy: 'Ministry of Tourism, India', tags: ['UNESCO', 'Rajasthan', 'Fort', 'Sheesh Mahal'],
    },
    {
        name: 'Mysore Palace',
        location: 'Mysuru, Karnataka', city: 'Mysuru', state: 'Karnataka',
        address: 'Sayyaji Rao Rd, Agrahara, Chamrajpura, Mysuru, Karnataka 570001',
        rating: 4.7,
        image: 'https://images.unsplash.com/photo-1580181128165-e6be16d760b2?auto=format&fit=crop&w=800&q=80',
        history: 'Mysore Palace is the official residence of the Wadiyar dynasty and seat of the Kingdom of Mysore. The current palace was built in 1912 by Henry Irwin in Indo-Saracenic style after the previous wooden palace burned down. It is one of the most visited monuments in India. The palace is illuminated by 97,000 light bulbs during Dasara festival, creating a breathtaking spectacle.',
        builtYear: '1897–1912', builtBy: 'Maharaja Krishnaraja Wadiyar IV',
        timings: '10:00 AM – 5:30 PM', entryFee: '₹100 (Indian) / ₹200 (Foreign)',
        distanceFromDelhi: '2,100 km', routeFromDelhi: 'Fly from IGI Airport to Mysuru Airport or Bengaluru Kempegowda Airport (then 3-hr drive). Rajdhani Express train from Delhi to Bengaluru (~33 hrs), then cab.',
        coordinates: { lat: 12.3052, lng: 76.6552 }, category: 'palace', isVerified: true,
        verifiedBy: 'Ministry of Tourism, India', tags: ['Karnataka', 'Royal Palace', 'Dasara', 'Indo-Saracenic'],
    },
    {
        name: 'Golden Temple (Harmandir Sahib)',
        location: 'Amritsar, Punjab', city: 'Amritsar', state: 'Punjab',
        address: 'Golden Temple Rd, Atta Mandi, Katra Ahluwalia, Amritsar, Punjab 143006',
        rating: 4.9,
        image: 'https://images.unsplash.com/photo-1588416499018-d8c621e1854f?auto=format&fit=crop&w=800&q=80',
        history: 'The Golden Temple (Harmandir Sahib) is the holiest shrine in Sikhism, built by Guru Arjan Dev in 1604. The upper floors are covered with 400 kg of pure gold, giving it its iconic appearance. The temple sits in the middle of the Amrit Sarovar (Pool of Nectar) and welcomes over 100,000 visitors daily regardless of religion, caste, or creed, offering free langar (community meal).',
        builtYear: '1577–1604', builtBy: 'Guru Ram Das & Guru Arjan Dev',
        timings: 'Open 24 hours', entryFee: 'Free',
        distanceFromDelhi: '450 km', routeFromDelhi: 'Take NH1 or NH44 — about 6 hrs by car. Shatabdi Express or Golden Temple Mail train from New Delhi Station to Amritsar Junction (5-6 hrs).',
        coordinates: { lat: 31.6200, lng: 74.8765 }, category: 'temple', isVerified: true,
        verifiedBy: 'Ministry of Tourism, India', tags: ['Sikhism', 'Holy Temple', 'Gold', 'Free Langar'],
    },
    {
        name: 'Meenakshi Amman Temple',
        location: 'Madurai, Tamil Nadu', city: 'Madurai', state: 'Tamil Nadu',
        address: 'Madurai Main, Madurai, Tamil Nadu 625001',
        rating: 4.8,
        image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80',
        history: 'The Meenakshi Amman Temple is a 2,500-year-old historic Hindu temple dedicated to Goddess Meenakshi and Lord Sundareshwara (Shiva). The present structure was built during the Nayak dynasty (1600s). It features 14 magnificent gateway towers (gopurams) covered with thousands of colorful sculptures. The tallest tower is 52 metres. The temple complex has 33,000 sculpted figures.',
        builtYear: '17th century (rebuilt)', builtBy: 'Nayak Dynasty',
        timings: '5:00 AM – 12:30 PM, 4:00 PM – 10:00 PM', entryFee: 'Free (Camera: ₹50)',
        distanceFromDelhi: '2,200 km', routeFromDelhi: 'Fly from IGI Airport to Madurai Airport (2.5 hrs). Grand Trunk Express train from Delhi to Madurai (~47 hrs).',
        coordinates: { lat: 9.9196, lng: 78.1192 }, category: 'temple', isVerified: true,
        verifiedBy: 'Ministry of Tourism, India', tags: ['Tamil Nadu', 'Hindu Temple', 'Gopuram', 'Ancient'],
    },
    {
        name: 'Charminar',
        location: 'Hyderabad, Telangana', city: 'Hyderabad', state: 'Telangana',
        address: 'Charminar Rd, Char Kaman, Ghansi Bazaar, Hyderabad, Telangana 500002',
        rating: 4.5,
        image: 'https://images.unsplash.com/photo-1605640840605-14ac1855827b?auto=format&fit=crop&w=800&q=80',
        history: 'Charminar (Four Minarets) was built in 1591 by Muhammad Quli Qutb Shah to commemorate the founding of Hyderabad and to mark the end of a plague epidemic. The 56-metre monument has four grand arches facing four directions and four minarets topped with domes. It houses a mosque on its top floor and is surrounded by the bustling Laad Bazaar famous for bangles and pearls.',
        builtYear: '1591', builtBy: 'Muhammad Quli Qutb Shah',
        timings: '9:30 AM – 5:30 PM', entryFee: '₹25 (Indian) / ₹300 (Foreign)',
        distanceFromDelhi: '1,570 km', routeFromDelhi: 'Fly from IGI Airport to Rajiv Gandhi International Airport Hyderabad (1.5 hrs). Telangana Express train from Delhi (~26 hrs).',
        coordinates: { lat: 17.3616, lng: 78.4747 }, category: 'monument', isVerified: true,
        verifiedBy: 'Ministry of Tourism, India', tags: ['Hyderabad', 'Qutb Shahi', 'Mosque', 'Bazaar'],
    },
    {
        name: 'Konark Sun Temple',
        location: 'Konark, Odisha', city: 'Konark', state: 'Odisha',
        address: 'Konark, Puri District, Odisha 752111',
        rating: 4.7,
        image: 'https://images.unsplash.com/photo-1621996659490-3275b4d0d951?auto=format&fit=crop&w=800&q=80',
        history: 'The Konark Sun Temple is a 13th-century UNESCO World Heritage Site dedicated to the Hindu sun god Surya. Built in 1250 CE by King Narasimhadeva I of the Eastern Ganga dynasty, it is designed as a giant chariot with 24 intricately carved stone wheels pulled by seven horses. The temple is renowned for its erotic sculptures and extraordinary stone carvings depicting everyday life.',
        builtYear: '1250 CE', builtBy: 'King Narasimhadeva I',
        timings: '6:00 AM – 8:00 PM', entryFee: '₹40 (Indian) / ₹600 (Foreign)',
        distanceFromDelhi: '1,850 km', routeFromDelhi: 'Fly from IGI to Bhubaneswar Airport (2 hrs), then 65 km drive to Konark. Purushottam Express train from Delhi to Bhubaneswar (~28 hrs).',
        coordinates: { lat: 19.8876, lng: 86.0944 }, category: 'heritage', isVerified: true,
        verifiedBy: 'Ministry of Tourism, India', tags: ['UNESCO', 'Odisha', 'Sun Temple', 'Stone Chariot'],
    },
    {
        name: 'Hampi (Vijayanagara Ruins)',
        location: 'Hampi, Karnataka', city: 'Hampi', state: 'Karnataka',
        address: 'Hampi, Vijayanagara District, Karnataka 583239',
        rating: 4.8,
        image: 'https://images.unsplash.com/photo-1583413000928-c1f01df80e3c?auto=format&fit=crop&w=800&q=80',
        history: 'Hampi is a UNESCO World Heritage Site and the ruined capital of the Vijayanagara Empire (1336–1646). Once one of the largest cities in the world with a population of 500,000, it contains over 1,600 surviving remains including temples, palaces, market streets, and elephant stables. The iconic Virupaksha Temple has been in continuous worship for over 1,000 years.',
        builtYear: '1336 CE onwards', builtBy: 'Vijayanagara Empire',
        timings: 'Open 24 hours (Monuments: 6:00 AM – 6:00 PM)', entryFee: '₹40 (Indian) / ₹600 (Foreign)',
        distanceFromDelhi: '1,800 km', routeFromDelhi: 'Fly from IGI to Hubli Airport or Bengaluru (then 6-hr drive). Hampi Express train from Bengaluru to Hospet Junction (9 hrs), then 13 km to Hampi.',
        coordinates: { lat: 15.3350, lng: 76.4600 }, category: 'heritage', isVerified: true,
        verifiedBy: 'Ministry of Tourism, India', tags: ['UNESCO', 'Ruins', 'Vijayanagara', 'Karnataka'],
    },
    {
        name: 'Ajanta Caves',
        location: 'Aurangabad, Maharashtra', city: 'Aurangabad', state: 'Maharashtra',
        address: 'Ajanta, Aurangabad District, Maharashtra 431117',
        rating: 4.7,
        image: 'https://images.unsplash.com/photo-1544568100-847a948585b9?auto=format&fit=crop&w=800&q=80',
        history: 'The Ajanta Caves are 30 rock-cut Buddhist cave monuments dating from the 2nd century BCE. A UNESCO World Heritage Site, they contain some of the finest surviving examples of ancient Indian art — paintings and sculptures depicting the Jataka tales (stories of Buddha\'s past lives). The caves were abandoned in the 7th century and rediscovered by a British officer in 1819.',
        builtYear: '2nd century BCE – 6th century CE', builtBy: 'Buddhist Monks & Patrons',
        timings: '9:00 AM – 5:30 PM (Closed Mondays)', entryFee: '₹40 (Indian) / ₹600 (Foreign)',
        distanceFromDelhi: '1,200 km', routeFromDelhi: 'Fly from IGI to Chikkalthana Airport Aurangabad (2 hrs). Tapovan Express train from Delhi to Aurangabad (~20 hrs), then 100 km to caves.',
        coordinates: { lat: 20.5519, lng: 75.7033 }, category: 'heritage', isVerified: true,
        verifiedBy: 'Ministry of Tourism, India', tags: ['UNESCO', 'Buddhist', 'Rock-Cut', 'Paintings'],
    },
    {
        name: 'Red Fort (Lal Qila)',
        location: 'Old Delhi, New Delhi', city: 'New Delhi', state: 'Delhi',
        address: 'Netaji Subhash Marg, Lal Qila, Chandni Chowk, New Delhi 110006',
        rating: 4.5,
        image: 'https://images.unsplash.com/photo-1585506942812-e72b29cef752?auto=format&fit=crop&w=800&q=80',
        history: 'Red Fort is a UNESCO World Heritage Site and historic Mughal fort built in 1648 by Emperor Shah Jahan in red sandstone. It served as the main residence of Mughal emperors for nearly 200 years. On August 15, 1947, India\'s first Prime Minister Jawaharlal Nehru hoisted the national flag here — a tradition continued by every Prime Minister on Independence Day. The fort houses several museums.',
        builtYear: '1638–1648', builtBy: 'Emperor Shah Jahan',
        timings: '9:30 AM – 4:30 PM (Closed Mondays)', entryFee: '₹35 (Indian) / ₹500 (Foreign)',
        distanceFromDelhi: '0 km (Old Delhi)', routeFromDelhi: 'Take Yellow Line Metro to Chandni Chowk Station — 5 min walk. Located in Old Delhi, easily accessible from all parts of the city.',
        coordinates: { lat: 28.6562, lng: 77.2410 }, category: 'heritage', isVerified: true,
        verifiedBy: 'Ministry of Tourism, India', tags: ['UNESCO', 'Mughal', 'Independence Day', 'Old Delhi'],
    },
    {
        name: 'Ellora Caves',
        location: 'Aurangabad, Maharashtra', city: 'Aurangabad', state: 'Maharashtra',
        address: 'Ellora, Aurangabad District, Maharashtra 431102',
        rating: 4.8,
        image: 'https://images.unsplash.com/photo-1603262110263-fb0112e7cc33?auto=format&fit=crop&w=800&q=80',
        history: 'Ellora is a UNESCO World Heritage Site with 34 rock-cut caves representing Buddhist, Hindu, and Jain traditions (6th–11th century CE). The Kailasa Temple (Cave 16) is the world\'s largest monolithic rock excavation — carved top-down from a single basalt cliff to represent Mount Kailash. About 200,000 tonnes of rock were excavated using only hand tools over a century.',
        builtYear: '600–1000 CE', builtBy: 'Rashtrakuta Dynasty & Others',
        timings: '6:00 AM – 6:00 PM (Closed Tuesdays)', entryFee: '₹40 (Indian) / ₹600 (Foreign)',
        distanceFromDelhi: '1,170 km', routeFromDelhi: 'Fly from IGI to Aurangabad Airport (2 hrs). Then 29 km drive to Ellora. Tapovan Express train from Delhi (~20 hrs).',
        coordinates: { lat: 20.0261, lng: 75.1790 }, category: 'heritage', isVerified: true,
        verifiedBy: 'Ministry of Tourism, India', tags: ['UNESCO', 'Kailasa Temple', 'Rock-Cut', 'Maharashtra'],
    },
    {
        name: 'Fatehpur Sikri',
        location: 'Agra District, Uttar Pradesh', city: 'Fatehpur Sikri', state: 'Uttar Pradesh',
        address: 'Fatehpur Sikri, Agra District, Uttar Pradesh 283110',
        rating: 4.6,
        image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=800&q=80',
        history: 'Fatehpur Sikri is a UNESCO World Heritage Site and a perfectly preserved Mughal city built by Emperor Akbar in 1571 as his capital. Abandoned just 14 years later due to water shortage, it remains one of the finest surviving examples of Mughal architecture. The Buland Darwaza (Gate of Magnificence) at 54 metres is the highest gateway in the world. The city blends Hindu, Islamic, and Jain styles.',
        builtYear: '1569–1585', builtBy: 'Emperor Akbar',
        timings: 'Sunrise to Sunset', entryFee: '₹50 (Indian) / ₹610 (Foreign)',
        distanceFromDelhi: '210 km', routeFromDelhi: 'Take Yamuna Expressway (NH19) to Agra, then 37 km west. Total ~3.5 hrs by car. Toofan Express from Delhi to Fatehpur Sikri Station (4 hrs).',
        coordinates: { lat: 27.0940, lng: 77.6615 }, category: 'heritage', isVerified: true,
        verifiedBy: 'Ministry of Tourism, India', tags: ['UNESCO', 'Mughal Empire', 'Akbar', 'Ghost City'],
    },
];

const hotels = [
    {
        name: 'Taj Palace',
        location: 'New Delhi', city: 'New Delhi', state: 'Delhi',
        address: '2, Sardar Patel Marg, Diplomatic Enclave, New Delhi 110021',
        rating: 5.0, pricePerNight: '₹12,000',
        image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
        description: 'The Taj Palace is a landmark luxury hotel in New Delhi\'s Diplomatic Enclave. Known for hosting world leaders and dignitaries, it features opulent rooms, award-winning restaurants, and an iconic dome. Home to the legendary Masala Art restaurant.',
        amenities: ['Free WiFi', 'Swimming Pool', 'Luxury Spa', 'Multiple Restaurants', 'Bar', 'Butler Service', 'Valet Parking', 'Concierge', 'Business Centre'],
        phone: '+91-11-2611-0202', website: 'https://www.tajhotels.com',
        distanceFromDelhi: '0 km (Located in Delhi)',
        routeFromDelhi: 'Diplomatic Enclave, New Delhi. Metro Violet Line to Khan Market. By road via Sardar Patel Marg.',
        coordinates: { lat: 28.5978, lng: 77.1756 }, category: 'luxury',
        checkIn: '2:00 PM', checkOut: '12:00 PM', totalRooms: 403,
        isVerified: true, verifiedBy: 'Ministry of Tourism, India',
        tags: ['5-Star', 'Diplomatic Enclave', 'Presidential', 'Award-Winning'],
    },
    {
        name: 'ITC Maurya',
        location: 'New Delhi', city: 'New Delhi', state: 'Delhi',
        address: 'Sardar Patel Marg, Diplomatic Enclave, New Delhi 110021',
        rating: 4.9, pricePerNight: '₹15,000',
        image: 'https://images.unsplash.com/photo-1551882547-ff43c63efe8c?auto=format&fit=crop&w=800&q=80',
        description: 'ITC Maurya is one of Delhi\'s most prestigious hotels, named after the Maurya Empire. It has hosted US Presidents and world leaders. Home to Bukhara — consistently ranked among Asia\'s best restaurants — and Dum Pukht for royal Awadhi cuisine.',
        amenities: ['Free WiFi', 'Swimming Pool', 'World-Class Spa', 'Bukhara Restaurant', 'Dum Pukht', 'Club Lounge', '24h Room Service', 'Valet Parking'],
        phone: '+91-11-2611-2233', website: 'https://www.itchotels.com',
        distanceFromDelhi: '0 km (Located in Delhi)',
        routeFromDelhi: 'Diplomatic Enclave. Metro to Udyog Bhawan (Yellow Line), short cab. Via Sardar Patel Marg.',
        coordinates: { lat: 28.5982, lng: 77.1742 }, category: 'luxury',
        checkIn: '2:00 PM', checkOut: '12:00 PM', totalRooms: 438,
        isVerified: true, verifiedBy: 'Ministry of Tourism, India',
        tags: ['5-Star', 'Presidential Suite', 'ITC', 'Fine Dining'],
    },
    {
        name: 'The Oberoi Udaivilas',
        location: 'Udaipur, Rajasthan', city: 'Udaipur', state: 'Rajasthan',
        address: 'Haridasji Ki Magri, Mulla Talai, Udaipur, Rajasthan 313001',
        rating: 5.0, pricePerNight: '₹45,000',
        image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80',
        description: 'Consistently voted one of the world\'s best hotels, Oberoi Udaivilas sits on the banks of Lake Pichola with magical views of the City Palace and Lake Palace. The hotel is built like a Rajput palace with domes, fountains, and stunning courtyards. A truly once-in-a-lifetime experience.',
        amenities: ['Free WiFi', 'Lake View Pool', 'Oberoi Spa', 'Fine Dining', 'Boat Safari', 'Yoga & Meditation', 'Butler Service', 'Complimentary Sunset Cruise'],
        phone: '+91-294-243-3300', website: 'https://www.oberoihotels.com',
        distanceFromDelhi: '660 km',
        routeFromDelhi: 'Fly from IGI Airport to Maharana Pratap Airport Udaipur (1.5 hrs). Chetak Express train from Delhi to Udaipur City Station (~12 hrs).',
        coordinates: { lat: 24.5774, lng: 73.6829 }, category: 'luxury',
        checkIn: '2:00 PM', checkOut: '12:00 PM', totalRooms: 90,
        isVerified: true, verifiedBy: 'Ministry of Tourism, India',
        tags: ['Best Hotel in World', 'Lake View', '5-Star', 'Rajasthan'],
    },
    {
        name: 'Umaid Bhawan Palace',
        location: 'Jodhpur, Rajasthan', city: 'Jodhpur', state: 'Rajasthan',
        address: 'Near Circuit House, Cantt Area, Jodhpur, Rajasthan 342006',
        rating: 4.9, pricePerNight: '₹35,000',
        image: 'https://images.unsplash.com/photo-1587974928442-77dc3e0dba72?auto=format&fit=crop&w=800&q=80',
        description: 'One of the world\'s largest private residences, Umaid Bhawan Palace is still home to the royal family. Part of it is a Taj-managed heritage hotel featuring Art Deco architecture, a vintage car collection, and views of the Blue City of Jodhpur. The award-winning Pillars restaurant serves royal Marwari cuisine.',
        amenities: ['Free WiFi', 'Royal Pool', 'Tennis Court', 'Heritage Spa', 'Museum', 'Vintage Cars Tour', 'Snooker Room', 'Butler Service'],
        phone: '+91-291-251-0101', website: 'https://www.tajhotels.com',
        distanceFromDelhi: '600 km',
        routeFromDelhi: 'Fly from IGI to Jodhpur Airport (1.5 hrs). Mandore Express or Suryanagri Express train from Delhi (~10 hrs).',
        coordinates: { lat: 26.2801, lng: 73.0444 }, category: 'heritage',
        checkIn: '2:00 PM', checkOut: '12:00 PM', totalRooms: 70,
        isVerified: true, verifiedBy: 'Ministry of Tourism, India',
        tags: ['Royal Palace', 'Heritage', 'Jodhpur', '5-Star'],
    },
    {
        name: 'Taj Mahal Palace Mumbai',
        location: 'Mumbai, Maharashtra', city: 'Mumbai', state: 'Maharashtra',
        address: 'Apollo Bunder, Colaba, Mumbai, Maharashtra 400001',
        rating: 5.0, pricePerNight: '₹28,000',
        image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80',
        description: 'Built in 1903, the Taj Mahal Palace Mumbai is an iconic heritage hotel overlooking the Gateway of India and the Arabian Sea. India\'s first luxury hotel, it has hosted royalty, celebrities, and world leaders. The Taj withstood the 26/11 terrorist attacks and is a symbol of Mumbai\'s resilience and spirit.',
        amenities: ['Free WiFi', 'Sea View Rooms', 'Swimming Pool', 'Jiva Spa', 'Multiple Award-Winning Restaurants', 'Rooftop Bar', 'Heritage Tour', 'Concierge'],
        phone: '+91-22-6665-3366', website: 'https://www.tajhotels.com',
        distanceFromDelhi: '1,400 km',
        routeFromDelhi: 'Fly from IGI to Chhatrapati Shivaji Maharaj International Airport Mumbai (2 hrs). Rajdhani Express train from Delhi to Mumbai Central (~16 hrs).',
        coordinates: { lat: 18.9217, lng: 72.8333 }, category: 'heritage',
        checkIn: '2:00 PM', checkOut: '12:00 PM', totalRooms: 560,
        isVerified: true, verifiedBy: 'Ministry of Tourism, India',
        tags: ['Iconic', 'Gateway of India', 'Heritage', 'Mumbai 5-Star'],
    },
    {
        name: 'The Leela Palace Bengaluru',
        location: 'Bengaluru, Karnataka', city: 'Bengaluru', state: 'Karnataka',
        address: '23, HAL Airport Road, Kodihalli, Bengaluru, Karnataka 560008',
        rating: 4.8, pricePerNight: '₹18,000',
        image: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?auto=format&fit=crop&w=800&q=80',
        description: 'The Leela Palace Bengaluru is an oasis of luxury in India\'s Silicon Valley. Inspired by the Hoysala temples, the hotel features intricate architecture, lush gardens, a grand ballroom, and the award-winning Jamavar restaurant. Ideal for business travellers and leisure guests alike.',
        amenities: ['Free WiFi', 'Swimming Pool', 'Spa & Wellness', 'Jamavar Restaurant', 'Citrus Café', 'Business Centre', 'Outdoor Tennis', 'Valet Parking'],
        phone: '+91-80-2521-1234', website: 'https://www.theleela.com',
        distanceFromDelhi: '2,100 km',
        routeFromDelhi: 'Fly from IGI to Kempegowda International Airport (2.5 hrs). Chennai Rajdhani Express from Delhi to Bengaluru City (~34 hrs).',
        coordinates: { lat: 12.9672, lng: 77.6432 }, category: 'luxury',
        checkIn: '2:00 PM', checkOut: '12:00 PM', totalRooms: 357,
        isVerified: true, verifiedBy: 'Ministry of Tourism, India',
        tags: ['5-Star', 'Bengaluru', 'Business', 'Leela Group'],
    },
    {
        name: 'Rambagh Palace',
        location: 'Jaipur, Rajasthan', city: 'Jaipur', state: 'Rajasthan',
        address: 'Bhawani Singh Rd, Rambagh, Jaipur, Rajasthan 302005',
        rating: 4.9, pricePerNight: '₹40,000',
        image: 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=800&q=80',
        description: 'Once the residence of the Maharaja of Jaipur, Rambagh Palace is Jaipur\'s most iconic heritage hotel. Known as the "Jewel of Jaipur," it offers royal suites with antique furniture, polo grounds, peacock gardens, and the legendary Suvarna Mahal restaurant serving royal Rajasthani cuisine in regal surroundings.',
        amenities: ['Free WiFi', 'Royal Pool', 'Polo Grounds', 'Suvarna Mahal Restaurant', 'Rajput Room Bar', 'Spa', 'Peacock Garden', 'Elephant Rides'],
        phone: '+91-141-221-1919', website: 'https://www.tajhotels.com',
        distanceFromDelhi: '282 km',
        routeFromDelhi: 'Take NH48 to Jaipur (4.5 hrs by car). Shatabdi Express or Pink City Express from New Delhi to Jaipur Junction (4.5 hrs), then 5 km cab.',
        coordinates: { lat: 26.8977, lng: 75.8069 }, category: 'heritage',
        checkIn: '2:00 PM', checkOut: '12:00 PM', totalRooms: 78,
        isVerified: true, verifiedBy: 'Ministry of Tourism, India',
        tags: ['Royal Palace', 'Jewel of Jaipur', 'Polo', 'Heritage'],
    },
    {
        name: 'Wildflower Hall Shimla',
        location: 'Shimla, Himachal Pradesh', city: 'Shimla', state: 'Himachal Pradesh',
        address: 'Chharabra, Shimla, Himachal Pradesh 171012',
        rating: 4.8, pricePerNight: '₹22,000',
        image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=800&q=80',
        description: 'Nestled at 8,250 ft in the Himalayas, Wildflower Hall is an Oberoi luxury resort set in 22 acres of cedar and rhododendron forest. The original building was the residence of Lord Kitchener. It offers breathtaking mountain views, outdoor adventures like skiing and trekking, and an iconic infinity pool overlooking the snow peaks.',
        amenities: ['Free WiFi', 'Himalayan View Infinity Pool', 'Luxury Spa', 'Mountain Dining', 'Skiing', 'Trekking', 'Outdoor Jacuzzi', 'Billiards'],
        phone: '+91-177-264-8585', website: 'https://www.oberoihotels.com',
        distanceFromDelhi: '370 km',
        routeFromDelhi: 'Take NH44 to Shimla via Chandigarh — 8 hrs by car. Shatabdi Express to Kalka (3.5 hrs), then Toy Train to Shimla (5 hrs).',
        coordinates: { lat: 31.0790, lng: 77.1860 }, category: 'luxury',
        checkIn: '2:00 PM', checkOut: '12:00 PM', totalRooms: 85,
        isVerified: true, verifiedBy: 'Ministry of Tourism, India',
        tags: ['Himalayan Resort', 'Shimla', 'Mountain View', 'Oberoi'],
    },
    {
        name: 'Kumarakom Lake Resort',
        location: 'Kumarakom, Kerala', city: 'Kumarakom', state: 'Kerala',
        address: 'Kumarakom North P.O., Kottayam, Kerala 686563',
        rating: 4.8, pricePerNight: '₹20,000',
        image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=80',
        description: 'Kumarakom Lake Resort is a luxury heritage resort on the banks of Vembanad Lake — Kerala\'s largest lake. Featuring traditional Kerala architecture with tiled roofs and open verandahs, the resort includes private pool villas, houseboats, Ayurvedic spa, and stunning backwater views at every turn.',
        amenities: ['Free WiFi', 'Vembanad Lake View', 'Infinity Pool', 'Ayurvedic Spa', 'Houseboat Cruise', 'Yoga & Meditation', 'Traditional Kerala Dining', 'Backwater Fishing'],
        phone: '+91-481-252-4900', website: 'https://www.kumarakomlakeresort.in',
        distanceFromDelhi: '2,600 km',
        routeFromDelhi: 'Fly from IGI to Cochin International Airport (2.5 hrs), then 50 km drive. Trivandrum Rajdhani train from Delhi to Kottayam (~40 hrs).',
        coordinates: { lat: 9.5833, lng: 76.4167 }, category: 'boutique',
        checkIn: '2:00 PM', checkOut: '11:00 AM', totalRooms: 106,
        isVerified: true, verifiedBy: 'Ministry of Tourism, India',
        tags: ['Kerala', 'Backwaters', 'Ayurveda', 'Heritage'],
    },
    {
        name: 'Samode Palace',
        location: 'Samode, Rajasthan', city: 'Samode', state: 'Rajasthan',
        address: 'Samode Village, Chomu Tehsil, Jaipur, Rajasthan 303806',
        rating: 4.7, pricePerNight: '₹18,000',
        image: 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80',
        description: 'Samode Palace is a 475-year-old royal fort palace that has been converted into a heritage hotel. Located 45 km from Jaipur, it features magnificent hand-painted Sheesh Mahal suites, royal courtyards, a rooftop pool, and an authentic Rajasthani experience in a less commercialized setting. Perfect for those seeking royal grandeur away from crowds.',
        amenities: ['Free WiFi', 'Rooftop Swimming Pool', 'Sheesh Mahal Suite', 'Rajasthani Dining', 'Camel Rides', 'Heritage Walk', 'Yoga', 'Cultural Evenings'],
        phone: '+91-141-263-2407', website: 'https://www.samode.com',
        distanceFromDelhi: '320 km',
        routeFromDelhi: 'Take NH48 to Jaipur (4.5 hrs), then 45 km north to Samode Village. Take Shatabdi to Jaipur, then cab.',
        coordinates: { lat: 27.1833, lng: 75.5833 }, category: 'heritage',
        checkIn: '2:00 PM', checkOut: '12:00 PM', totalRooms: 43,
        isVerified: true, verifiedBy: 'Ministry of Tourism, India',
        tags: ['Heritage Palace', 'Boutique', 'Rajasthan', 'Royal'],
    },
    {
        name: 'Vivanta Goa Panaji',
        location: 'Panaji, Goa', city: 'Panaji', state: 'Goa',
        address: 'Miramar Beach, Panaji, Goa 403001',
        rating: 4.6, pricePerNight: '₹10,000',
        image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=80',
        description: 'Vivanta Goa is a stylish beach resort at Miramar Beach with panoramic views of the Arabian Sea and Mandovi River. Just minutes from Panaji city, it combines beachside relaxation with urban convenience. Features a rooftop pool, Goan and international cuisine, and easy access to Old Goa\'s Portuguese heritage.',
        amenities: ['Free WiFi', 'Beachfront Location', 'Rooftop Pool', 'Spa', 'Multi-Cuisine Restaurant', 'Bar', 'Water Sports', 'Firefly Café'],
        phone: '+91-832-664-7777', website: 'https://www.vivantahotels.com',
        distanceFromDelhi: '1,900 km',
        routeFromDelhi: 'Fly from IGI to Dabolim Airport or Manohar Goa Airport (2.5 hrs). Rajdhani Express train from Delhi to Madgaon (~26 hrs), then 29 km cab.',
        coordinates: { lat: 15.4785, lng: 73.8006 }, category: 'business',
        checkIn: '2:00 PM', checkOut: '12:00 PM', totalRooms: 155,
        isVerified: true, verifiedBy: 'Ministry of Tourism, India',
        tags: ['Goa', 'Beach Resort', 'Miramar', 'Sea View'],
    },
    {
        name: 'Taj Falaknuma Palace',
        location: 'Hyderabad, Telangana', city: 'Hyderabad', state: 'Telangana',
        address: 'Engine Bowli, Falaknuma, Hyderabad, Telangana 500053',
        rating: 5.0, pricePerNight: '₹38,000',
        image: 'https://images.unsplash.com/photo-1606046604972-77cc76aee944?auto=format&fit=crop&w=800&q=80',
        description: 'Perched on a hilltop 2,000 ft above Hyderabad, Taj Falaknuma Palace was the private residence of the Nizam of Hyderabad — once the world\'s richest man. The palace has 60 rooms and 22 halls and took 9 years to build. Guests arrive by horse-drawn carriage. The Jade Room boasts the world\'s largest jade collection outside China.',
        amenities: ['Free WiFi', 'Palace Tour', 'Horse Carriage Arrival', 'Royal Pool', 'Adaa Restaurant (Nizami Cuisine)', 'Cellar Bar', 'Jade Room', 'Butler Service'],
        phone: '+91-40-6629-8585', website: 'https://www.tajhotels.com',
        distanceFromDelhi: '1,570 km',
        routeFromDelhi: 'Fly from IGI to Rajiv Gandhi International Airport Hyderabad (1.5 hrs), then 40 km cab. Telangana Express train from Delhi (~26 hrs).',
        coordinates: { lat: 17.3385, lng: 78.4638 }, category: 'heritage',
        checkIn: '2:00 PM', checkOut: '12:00 PM', totalRooms: 60,
        isVerified: true, verifiedBy: 'Ministry of Tourism, India',
        tags: ['Nizam Palace', 'Heritage', '5-Star', 'Hyderabad'],
    },
    {
        name: 'Ananda in the Himalayas',
        location: 'Narendra Nagar, Uttarakhand', city: 'Narendra Nagar', state: 'Uttarakhand',
        address: 'The Palace Estate, Narendra Nagar, Tehri Garhwal, Uttarakhand 249175',
        rating: 4.9, pricePerNight: '₹55,000',
        image: 'https://images.unsplash.com/photo-1461175827210-5ceac3e39dd2?auto=format&fit=crop&w=800&q=80',
        description: 'Ananda in the Himalayas is one of the world\'s finest destination spas. Set in a 100-acre maharaja\'s palace estate overlooking the Ganges and the town of Rishikesh, it specializes in traditional Ayurveda, yoga, and Vedanta. It has won countless "World\'s Best Spa" awards for its transformative wellness programs.',
        amenities: ['Free WiFi', 'World-Class Ayurvedic Spa', 'Yoga & Meditation', 'Ganges View', 'Organic Cuisine', 'Tennis Courts', 'Trekking', 'Palace Heritage Tour'],
        phone: '+91-1378-227-500', website: 'https://www.anandaspa.com',
        distanceFromDelhi: '260 km',
        routeFromDelhi: 'Take NH334 via Haridwar/Rishikesh — 5.5 hrs by car. Shatabdi Express to Haridwar (4.5 hrs), then 25 km cab to Narendra Nagar.',
        coordinates: { lat: 30.1850, lng: 78.2540 }, category: 'boutique',
        checkIn: '3:00 PM', checkOut: '11:00 AM', totalRooms: 75,
        isVerified: true, verifiedBy: 'Ministry of Tourism, India',
        tags: ['Wellness', 'Ayurveda', 'Himalayas', "World's Best Spa"],
    },
    {
        name: 'The Park Chennai',
        location: 'Chennai, Tamil Nadu', city: 'Chennai', state: 'Tamil Nadu',
        address: '601, Anna Salai, Chennai, Tamil Nadu 600006',
        rating: 4.5, pricePerNight: '₹7,500',
        image: 'https://images.unsplash.com/photo-1551876467-3b716b78fa48?auto=format&fit=crop&w=800&q=80',
        description: 'The Park Chennai is a design-forward luxury hotel on Chennai\'s prestigious Anna Salai. Known for its bold, contemporary interiors and vibrant nightlife, it houses Leather Bar — one of India\'s iconic bars — and Aqua rooftop pool bar. A favourite of business travelers and leisure guests visiting South India\'s bustling cultural capital.',
        amenities: ['Free WiFi', 'Rooftop Aqua Pool', 'Leather Bar', 'Aish Restaurant', 'Spa', 'Fitness Centre', 'Business Centre', 'Valet Parking'],
        phone: '+91-44-4267-6000', website: 'https://www.theparkhotels.com',
        distanceFromDelhi: '2,200 km',
        routeFromDelhi: 'Fly from IGI to Chennai International Airport (2.5 hrs). Grand Trunk Express train from Delhi to Chennai Central (~32 hrs).',
        coordinates: { lat: 13.0650, lng: 80.2536 }, category: 'business',
        checkIn: '2:00 PM', checkOut: '12:00 PM', totalRooms: 214,
        isVerified: true, verifiedBy: 'Ministry of Tourism, India',
        tags: ['Chennai', 'Design Hotel', 'Business', 'Rooftop Pool'],
    },
    {
        name: 'Treebo Trend Haridwar',
        location: 'Haridwar, Uttarakhand', city: 'Haridwar', state: 'Uttarakhand',
        address: 'Near Har Ki Pauri, Haridwar, Uttarakhand 249401',
        rating: 4.2, pricePerNight: '₹2,500',
        image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
        description: 'A clean, comfortable, and affordable hotel just steps from Har Ki Pauri — the most sacred ghat in Haridwar. Perfect for pilgrims visiting the Ganga Aarti and spiritual seekers. The hotel offers clean rooms, vegetarian meals, 24/7 hot water, and easy access to temples and ghats.',
        amenities: ['Free WiFi', 'Hot Water 24/7', 'Vegetarian Restaurant', 'Room Service', 'Tour Assistance', 'Luggage Storage', '24h Reception'],
        phone: '+91-1334-226-789', website: 'https://www.treebo.com',
        distanceFromDelhi: '210 km',
        routeFromDelhi: 'Take NH334 via Meerut and Muzaffarnagar — 4.5 hrs by car. Jan Shatabdi Express from Delhi to Haridwar (4.5 hrs).',
        coordinates: { lat: 29.9457, lng: 78.1642 }, category: 'budget',
        checkIn: '12:00 PM', checkOut: '11:00 AM', totalRooms: 42,
        isVerified: true, verifiedBy: 'Ministry of Tourism, India',
        tags: ['Budget', 'Pilgrimage', 'Haridwar', 'Ganga Aarti'],
    },
];

async function seed() {
    await mongoose.connect(MONGO_URI);
    console.log('✅ Connected to MongoDB:', MONGO_URI);

    // Clear existing
    await Place.deleteMany({});
    await Hotel.deleteMany({});
    console.log('🗑️  Cleared existing places and hotels');

    // Insert places
    const insertedPlaces = await Place.insertMany(places);
    console.log(`✅ Inserted ${insertedPlaces.length} Indian heritage places`);

    // Insert hotels
    const insertedHotels = await Hotel.insertMany(hotels);
    console.log(`✅ Inserted ${insertedHotels.length} verified Indian hotels`);

    console.log('\n🎉 Seeding complete!');
    console.log(`   Places: ${insertedPlaces.length}`);
    console.log(`   Hotels: ${insertedHotels.length}`);

    await mongoose.disconnect();
    process.exit(0);
}

seed().catch(err => {
    console.error('❌ Seed failed:', err);
    process.exit(1);
});
